import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen flex-col`}
      >
        <main className="flex-auto">{children}</main>
        <footer className="site-footer">
          <div className="container">
            <nav className="footer-nav">
              <a href="/page1">Page 1</a>
              <a href="/page2">Page 2</a>
              <a href="/page3">Page 3</a>
              <a href="/page4">Page 4</a>
              <a href="/page5">Page 5</a>
              <a href="/page6">Page 6</a>
            </nav>
            <div className="footer-credit">
              <span className="font-mono">Cool pages • built with Next</span>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
